[package]
name = "reqwasm"
version = "0.2.1"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/hamza1311/reqwasm"
description = "HTTP requests library for WASM Apps"
readme = "README.md"
keywords = ["requests", "http", "wasm", "websockets"]
categories = ["wasm", "web-programming::http-client", "api-bindings"]
exclude = [
    ".idea",
]

[dependencies]
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"
wasm-bindgen-futures = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
futures = "0.3.14"
gloo-utils = "0.1.0"

async-broadcast = "0.3"
pin-project = "1"

[dependencies.web-sys]
version = "0.3.4"
features = [
    'Headers',
    'Request',
    'RequestInit',
    'RequestMode',
    'Response',
    'Window',
    'RequestCache',
    'RequestCredentials',
    'ObserverCallback',
    'RequestRedirect',
    'ReferrerPolicy',
    'AbortSignal',
    'ReadableStream',
    'Blob',
    'FormData',
    'FileReader',
    'CloseEvent',

    'WebSocket',
    'ErrorEvent',
    'FileReader',
    'MessageEvent',
    'ProgressEvent',
    'BinaryType',
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
